<a href="https://colab.research.google.com/github/p0mona/university_data_analysis_methods/blob/main/mad_lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
import numpy as np

#Zadanie 1
Stwórz tablicę o nazwie a_small_one o wymiarach 8x8 z wartościami od 1 do 64.



In [108]:
a_small_one = np.arange(1, 65).reshape((8, 8))
a_small_one

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

#Zadanie 2

dla tablicy a_small_one policz:

-sumę dla każdej kolumny,

-sumę skumulowaną dla każdego wiersza,

-wartość średnią dla każdego wiersza,

In [109]:
print(f'Suma dla każdej kolumny: {a_small_one.sum(axis=0)}')
print(f'Suma skumulowana dla każdego wiersza:\n{a_small_one.cumsum(axis=1)}')
print(f'Wartość średnia dla każdego wiersza: {a_small_one.mean(axis=1)}')

Suma dla każdej kolumny: [232 240 248 256 264 272 280 288]
Suma skumulowana dla każdego wiersza:
[[  1   3   6  10  15  21  28  36]
 [  9  19  30  42  55  69  84 100]
 [ 17  35  54  74  95 117 140 164]
 [ 25  51  78 106 135 165 196 228]
 [ 33  67 102 138 175 213 252 292]
 [ 41  83 126 170 215 261 308 356]
 [ 49  99 150 202 255 309 364 420]
 [ 57 115 174 234 295 357 420 484]]
Wartość średnia dla każdego wiersza: [ 4.5 12.5 20.5 28.5 36.5 44.5 52.5 60.5]


#Zadanie 3
Zwróć podtablicę z tablicy a_small_one z elementami parzystymi (nie nadpisuj tej zmiennej).

In [110]:
a_small_one[a_small_one % 2 == 0].reshape(8, 4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48],
       [50, 52, 54, 56],
       [58, 60, 62, 64]])

#Zadanie 4
Zapisz do zmiennej o nazwie no_even_small_one tablicę a_small_one zamieniając wartości parzyste na wartość np.nan.

In [111]:
no_even_small_one = a_small_one.copy().astype(float)
no_even_small_one[a_small_one % 2 == 0] = np.nan
no_even_small_one

array([[ 1., nan,  3., nan,  5., nan,  7., nan],
       [ 9., nan, 11., nan, 13., nan, 15., nan],
       [17., nan, 19., nan, 21., nan, 23., nan],
       [25., nan, 27., nan, 29., nan, 31., nan],
       [33., nan, 35., nan, 37., nan, 39., nan],
       [41., nan, 43., nan, 45., nan, 47., nan],
       [49., nan, 51., nan, 53., nan, 55., nan],
       [57., nan, 59., nan, 61., nan, 63., nan]])

#Zadanie 5
Dla tablicy no_even_small_one policz funkcjami uwzględniającymi wartości nan (zazwyczaj posiadają przedrostek nan):

-sumę dla każdego wiersza,

-średnią dla każdej kolumny,

-wartość najmniejszą w całej tablicy,

In [112]:
print(f'Suma dla każdego wiersza: {np.nansum(no_even_small_one, axis=1)}')
print(f'Średnia dla każdej kolumny: {no_even_small_one.mean(axis=0)}')

Suma dla każdego wiersza: [ 16.  48.  80. 112. 144. 176. 208. 240.]
Średnia dla każdej kolumny: [29. nan 31. nan 33. nan 35. nan]


#Zadanie 6
Do tablicy no_even_small_one wstaw za pomocą funkcji np.where:

-wartości 1 dla każdej wartości np.nan (zobacz wbudowaną funkcję np.isnan())

-liczby parzyste, które wcześniej zastąpiliśmy wartościami nan (teraz 1 jeżeli wykonany jest podpunkt pierwszy), więc przywracamy ten tablicy wygląd oryginalny z tablicy a_small_one - dla warunku wstawiaj wartość z a_small_one lub no_even_small_one

In [113]:
no_even_small_one = np.where(np.isnan(no_even_small_one), 1, no_even_small_one)
no_even_small_one


array([[ 1.,  1.,  3.,  1.,  5.,  1.,  7.,  1.],
       [ 9.,  1., 11.,  1., 13.,  1., 15.,  1.],
       [17.,  1., 19.,  1., 21.,  1., 23.,  1.],
       [25.,  1., 27.,  1., 29.,  1., 31.,  1.],
       [33.,  1., 35.,  1., 37.,  1., 39.,  1.],
       [41.,  1., 43.,  1., 45.,  1., 47.,  1.],
       [49.,  1., 51.,  1., 53.,  1., 55.,  1.],
       [57.,  1., 59.,  1., 61.,  1., 63.,  1.]])

In [114]:
no_even_small_one = np.where(no_even_small_one == 1, a_small_one, no_even_small_one)
no_even_small_one

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16.],
       [17., 18., 19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30., 31., 32.],
       [33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48.],
       [49., 50., 51., 52., 53., 54., 55., 56.],
       [57., 58., 59., 60., 61., 62., 63., 64.]])

#Zadanie 7
Stwórz tablicę o nazwie sto_by_sto o wymiarach 100x100 próbkując wartości z rozkładu normalnego standardowego.

In [115]:
rng = np.random.default_rng()
sto_by_sto = rng.standard_normal((100, 100))
sto_by_sto

array([[-8.91097531e-02, -5.22283306e-01, -3.09352466e-01, ...,
        -4.51462123e-03, -5.90449483e-01, -9.00432515e-01],
       [ 1.63474450e+00, -1.53013392e+00, -2.57563747e-03, ...,
        -6.52623738e-01,  1.11108103e+00,  4.70667739e-01],
       [-5.99228280e-01, -4.32606315e-01, -2.89936396e+00, ...,
        -6.85146533e-01, -1.26045885e+00,  4.13018968e-01],
       ...,
       [ 7.72524928e-01,  6.61918500e-01,  1.54123717e+00, ...,
         5.98021861e-01,  4.10850209e-01,  5.66890796e-01],
       [ 7.10686261e-01, -6.34454993e-01,  1.85542241e+00, ...,
         7.07435412e-01, -1.93920408e+00, -5.97895934e-01],
       [ 5.65288871e-01, -3.40444124e-02, -1.85543126e-02, ...,
        -6.96898105e-01,  2.25916483e+00,  6.40529813e-01]])

#Zadanie 8
Dla tablicy sto_by_sto policz:

-wartość średnią w każdym wierszu i kolumnie (oddzielnie),

-policz średnią różnicę bezwzględną dla wartości w powyższym punkcie względem wartości 0 (oddzielnie dla średniej z kolumn i średniej z wierszy, pamiętam o tym, że operacje na tablicy numpy wykonywane są w trybie broadcast).

In [116]:
column = sto_by_sto.mean(axis=0)
row = sto_by_sto.mean(axis=1)
print(f'Wartość średnia w kolumnie:\n{column}')
print(f'\nWartość średnia w wierszu:\n{row}')

Wartość średnia w kolumnie:
[-0.13407962 -0.22648151 -0.11913857  0.13150115  0.02450906  0.09321839
 -0.03849718 -0.07570223  0.06602505 -0.00615295 -0.03553382  0.03872624
  0.10994744  0.0387245  -0.03542836  0.00767016 -0.05263123  0.09759342
 -0.07180802 -0.10354682  0.14500856  0.01628029  0.06032142 -0.08086708
  0.06704357  0.07541058 -0.07282473 -0.01160145  0.01520862 -0.06884121
  0.07488904  0.13198913 -0.02929146 -0.09631029 -0.02426375  0.10217876
  0.03069017 -0.18312773  0.0186569  -0.03506021 -0.097415    0.1158761
 -0.0084042   0.04301213 -0.11913187  0.11030028 -0.06943758 -0.18668877
 -0.04237221  0.10336027  0.05699937  0.08293903 -0.0301017  -0.18632166
 -0.07383076  0.0863907   0.07479606 -0.00036092  0.03374084 -0.09934128
 -0.04898754 -0.12150227  0.062566    0.04329401  0.08754813 -0.09873954
  0.08590557  0.07216791 -0.01378303 -0.01611394  0.02068277  0.01750457
  0.08728649 -0.07250289  0.19885397 -0.01259987 -0.03632993 -0.03478768
 -0.01499104 -0.06066309

In [53]:
print(f'Średnia różnica bezwzględna dla wartości w powyższym punkcie względem wartości 0 dla kolumn:\n{np.abs(column)}')
print(f'\nŚrednia różnica bezwzględna dla wartości w powyższym punkcie względem wartości 0 dla wierszy:\n{np.abs(row)}')

Średnia różnica bezwzględna dla wartości w powyższym punkcie względem wartości 0 dla kolumn:
[0.01798563 0.00905684 0.05508835 0.13489435 0.16743041 0.00670709
 0.10392527 0.02795648 0.06223816 0.10768427 0.08199684 0.02995896
 0.13449349 0.1248202  0.15046863 0.19428301 0.25231592 0.14082274
 0.04513117 0.10017683 0.09536335 0.08122922 0.11509521 0.08460661
 0.05003588 0.12263445 0.01281239 0.02888004 0.04343731 0.034188
 0.06047358 0.01943138 0.06114515 0.20685062 0.18379009 0.13662038
 0.15574299 0.05770671 0.03892688 0.04178319 0.06403225 0.13731471
 0.00496088 0.0593023  0.01034116 0.07359287 0.00541701 0.06242862
 0.07072178 0.0888144  0.13581447 0.06281958 0.0597149  0.051296
 0.0263889  0.04893924 0.00569734 0.10006558 0.02335679 0.05188747
 0.02647336 0.09767927 0.07162116 0.03060639 0.07761589 0.01053342
 0.02004872 0.31498954 0.01698866 0.07844758 0.03156467 0.01326749
 0.06127015 0.0627252  0.087085   0.09614101 0.12006714 0.00689824
 0.05658435 0.07910408 0.08372352 0.1867

#Zadanie 9
Stwórz tablicę o wymiarach 1000x1000 uzupełniając ją wartościami losowymi z rozkładu normalnego standardowego, a następnie posiłkując się przykładami z labów poprzednich (moduł timeit) porównaj czasy wykonania dla tej tablicy:

-zapisu do pliku tekstowego vs. zapis do pliku w formacie picle vs. zapis do pliku skompresowanego (funkcja savez_compressed w dokumentacji biblioteki numpy)

-odczytu dla trzech wyżej wymienionych plików.

In [79]:
from timeit import timeit

arr = rng.standard_normal((1000, 1000))

In [92]:
stmt1 = '''np.savetxt('arr.txt', arr)'''
stmt2 = '''pickle.dump(arr, open('arr.pkl', 'wb'))'''
stmt3 = '''np.savez_compressed('arr.npz', arr)'''

setup1 = '''
import numpy as np
import pickle
rng = np.random.default_rng()
arr = rng.standard_normal((1000, 1000))
'''

In [94]:
timeit(stmt = stmt1, setup = setup1, number = 10), timeit(stmt = stmt2, setup = setup1, number = 10), timeit(stmt = stmt3, setup = setup1, number = 10)

(9.65091460000076, 0.16326805599965155, 5.3408976970004005)

In [105]:
stmt4 = '''np.loadtxt('arr.txt')'''
stmt5 = '''with open('arr.pkl', 'rb') as f:
          arr = pickle.load(f)'''
stmt6 = '''np.load('arr.npz')'''

In [104]:
timeit(stmt = stmt4, setup = setup1, number = 1), timeit(stmt = stmt5, setup = setup1, number = 1), timeit(stmt = stmt6, setup = setup1, number = 1)

(0.5074495749995549, 0.0032194920004258165, 0.0028814449997298652)