<a href="https://colab.research.google.com/github/p0mona/university_data_analysis_methods/blob/main/mad_lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

#Zadanie 1

Stwórz tablicę numpy o wymiarach (4,4) wypełnioną wartościami od 2 do 32 z krokiem 2 i przypisz ją do zmiennej. Wyświetl jej typ danch, liczbę elementów, wielkość pojedynczego elementu oraz ilość zaalokowanej pamięci.

In [2]:
table = np.arange(2, 33, 2).reshape(4, 4)

print(f"Typ danych: {table.dtype}")
print(f"Liczba elementów: {table.size}")
print(f"Wielkość pojedynczego elementu: {table.itemsize}")
print(f"Ilość zaalokowanej pamięci: {table.nbytes}")

Typ danych: int64
Liczba elementów: 16
Wielkość pojedynczego elementu: 8
Ilość zaalokowanej pamięci: 128


#Zadanie 2

Zwróć tablicę z zadania 1 jako widok. Zmień jej typ danych (możesz to zrobić np. funkcją astype()) na np.uint8. Sprawdź teraz czy tablica jest widokiem czy kopią tablicy oryginalnej. Wyświetl jej liczbę elementów, wielkość pojedynczego elementu oraz ilość zaalokowanej pamięci.

In [3]:
table_view = table.view()

In [4]:
# Zmiana typu danych
table_view = table_view.astype(np.uint8)

In [5]:
# Czy tablica jest widokiem?
print(f"Czy tablica jest widokiem? {table_view.base is table.base}")

Czy tablica jest widokiem? False


In [6]:
print(f"Liczba elementów: {table_view.size}")
print(f"Wielkość pojedynczego elementu: {table_view.itemsize}")
print(f"Ilość zaalokowanej pamięci: {table_view.nbytes}")

Liczba elementów: 16
Wielkość pojedynczego elementu: 1
Ilość zaalokowanej pamięci: 16


In [7]:
table_view.base is table.base

False

#Zadanie 3

Wytnij z tablicy z zadania 1 obszar 2 x 2 "ze środka" tablicy (wartości 12,14, 20,22) na dwa sposoby:

-jeden jako widok i przypisz do zmiennej

-drugi jako kopia i przypisz do zmiennej

Posługując się przykładami z zajęć sprawdź czy baza tych dwóch tablic jest różna (powinna być).

In [8]:
# jako widok
widok = table[1:3, 1:3]
widok

array([[12, 14],
       [20, 22]])

In [9]:
# jako kopia
row = np.array([1, 1, 2, 2])
col = np.array([1, 2, 1, 2])
kopia = table[row, col].reshape(2, 2)
kopia

array([[12, 14],
       [20, 22]])

In [10]:
# Sprawdzanie bazy
print(widok.base is kopia.base)

False


#Zadanie 4

Stwórz tablicę 4x4, która zawiera wartości 1,2,3,4 w każdym wierszu. Następnie wykorzystując funkcje łączenia tablic utwórz tablicę połączoną z powyższej tablicy i jej wersji lustrzanej w poziomie (spróbuj użyć wycinków).

In [11]:
arr = np.array([1, 2, 3, 4] * 4).reshape(4, 4)
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [12]:
arr_h = arr[:, :: -1]
arr_h

array([[4, 3, 2, 1],
       [4, 3, 2, 1],
       [4, 3, 2, 1],
       [4, 3, 2, 1]])

In [16]:
arr_concat = np.concatenate((arr, arr_h), axis=1)
arr_concat

array([[1, 2, 3, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 3, 2, 1],
       [1, 2, 3, 4, 4, 3, 2, 1]])

#Zadanie 5

Utwórz tablicę o nazwie Z_5 o wymiarach 2x2 wypełnioną wartościami 1. Wykorzystując funkcje łączenia tabel uwtórz tablicę, która finalnie będzie tablicą składającą się z 4-ech tablic Z_5, ale tak aby finalnie była to tablica 4 x 4 podobna do poniższej:

1,1,2,2

1,1,2,2

3,3,4,4

3,3,4,4

In [14]:
Z_5 = np.tile([1, 1], 2).reshape(2, 2)


In [15]:
result = np.concatenate((np.concatenate((Z_5, Z_5 * 2), axis=1), np.concatenate((Z_5 * 2 + Z_5, Z_5 * 4), axis=1)), axis=0)
result

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])